/*
 * Configuration.
 */

// Fetch.
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_PENDING = 'FETCH_CONFIGURATION_PENDING';
export const FETCH_CONFIGURATION_REJECTED = 'FETCH_CONFIGURATION_REJECTED';
export const FETCH_CONFIGURATION_FULFILLED = 'FETCH_CONFIGURATION_FULFILLED';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const CLOSE_NOTIFICATION_PENDING = 'CLOSE_NOTIFICATION_PENDING';
export const CLOSE_NOTIFICATION_FULFILLED = 'CLOSE_NOTIFICATION_FULFILLED';
export const CLOSE_NOTIFICATION_REJECTED = 'CLOSE_NOTIFICATION_REJECTED';
export const CONFIRM_NOTIFICATION = 'CONFIRM_NOTIFICATION';
export const CONFIRM_NOTIFICATION_PENDING = 'CONFIRM_NOTIFICATION_PENDING';
export const CONFIRM_NOTIFICATION_FULFILLED = 'CONFIRM_NOTIFICATION_FULFILLED';
export const CONFIRM_NOTIFICATION_REJECTED = 'CONFIRM_NOTIFICATION_REJECTED';

/*
 * Deployments.
 */
export const OPEN_DEPLOYMENT = 'OPEN_DEPLOYMENT';
export const CLEAR_DEPLOYMENT = 'CLEAR_DEPLOYMENT';

// Fetch.
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';
export const FETCH_DEPLOYMENTS_PENDING = 'FETCH_DEPLOYMENTS_PENDING';
export const FETCH_DEPLOYMENTS_REJECTED = 'FETCH_DEPLOYMENTS_REJECTED';
export const FETCH_DEPLOYMENTS_FULFILLED = 'FETCH_DEPLOYMENTS_FULFILLED';

// Fetch.
export const FETCH_RULES = 'FETCH_RULES';
export const FETCH_RULES_PENDING = 'FETCH_RULES_PENDING';
export const FETCH_RULES_REJECTED = 'FETCH_RULES_REJECTED';
export const FETCH_RULES_FULFILLED = 'FETCH_RULES_FULFILLED';
export const FETCH_MANUAL_RULES = 'FETCH_MANUAL_RULES';
export const FETCH_MANUAL_RULES_PENDING = 'FETCH_MANUAL_RULES_PENDING';
export const FETCH_MANUAL_RULES_REJECTED = 'FETCH_MANUAL_RULES_REJECTED';
export const FETCH_MANUAL_RULES_FULFILLED = 'FETCH_MANUAL_RULES_FULFILLED';

export const UPDATE_MANUAL_RULES = 'UPDATE_MANUAL_RULES';
export const UPDATE_MANUAL_RULES_PENDING = 'UPDATE_MANUAL_RULES_PENDING';
export const UPDATE_MANUAL_RULES_REJECTED = 'UPDATE_MANUAL_RULES_REJECTED';
export const UPDATE_MANUAL_RULES_FULFILLED = 'UPDATE_MANUAL_RULES_FULFILLED';

export const FETCH_RESOURCE_SERVERS = 'FETCH_RESOURCE_SERVERS';
export const FETCH_RESOURCE_SERVERS_PENDING = 'FETCH_RESOURCE_SERVERS_PENDING';
export const FETCH_RESOURCE_SERVERS_REJECTED = 'FETCH_RESOURCE_SERVERS_REJECTED';
export const FETCH_RESOURCE_SERVERS_FULFILLED = 'FETCH_RESOURCE_SERVERS_FULFILLED';
export const FETCH_MANUAL_RESOURCE_SERVERS = 'FETCH_MANUAL_RESOURCE_SERVERS';
export const FETCH_MANUAL_RESOURCE_SERVERS_PENDING = 'FETCH_MANUAL_RESOURCE_SERVERS_PENDING';
export const FETCH_MANUAL_RESOURCE_SERVERS_REJECTED = 'FETCH_MANUAL_RESOURCE_SERVERS_REJECTED';
export const FETCH_MANUAL_RESOURCE_SERVERS_FULFILLED = 'FETCH_MANUAL_RESOURCE_SERVERS_FULFILLED';
export const UPDATE_MANUAL_RESOURCE_SERVERS = 'UPDATE_MANUAL_RESOURCE_SERVERS';
export const UPDATE_MANUAL_RESOURCE_SERVERS_PENDING = 'UPDATE_MANUAL_RESOURCE_SERVERS_PENDING';
export const UPDATE_MANUAL_RESOURCE_SERVERS_REJECTED = 'UPDATE_MANUAL_RESOURCE_SERVERS_REJECTED';
export const UPDATE_MANUAL_RESOURCE_SERVERS_FULFILLED = 'UPDATE_MANUAL_RESOURCE_SERVERS_FULFILLED';

// Run.
export const RUN_DEPLOYMENT = 'RUN_DEPLOYMENT';
export const RUN_DEPLOYMENT_PENDING = 'RUN_DEPLOYMENT_PENDING';
export const RUN_DEPLOYMENT_REJECTED = 'RUN_DEPLOYMENT_REJECTED';
export const RUN_DEPLOYMENT_FULFILLED = 'RUN_DEPLOYMENT_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Notifications
export const OPEN_RULE_NOTIFICATION = 'OPEN_RULE_NOTIFICATION';
export const CLOSE_RULE_NOTIFICATION = 'CLOSE_RULE_NOTIFICATION';
export const OPEN_RESOURCE_SERVER_NOTIFICATION = 'OPEN_RESOURCE_SERVER_NOTIFICATION';
export const CLOSE_RESOURCE_SERVER_NOTIFICATION = 'CLOSE_RESOURCE_SERVER_NOTIFICATION';
