/*
 * Configuration.
 */

// Fetch.
export const FETCH_CONFIGURATION = 'FETCH_CONFIGURATION';
export const FETCH_CONFIGURATION_PENDING = 'FETCH_CONFIGURATION_PENDING';
export const FETCH_CONFIGURATION_REJECTED = 'FETCH_CONFIGURATION_REJECTED';
export const FETCH_CONFIGURATION_FULFILLED = 'FETCH_CONFIGURATION_FULFILLED';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';
export const CLOSE_NOTIFICATION_PENDING = 'CLOSE_NOTIFICATION_PENDING';
export const CLOSE_NOTIFICATION_FULFILLED = 'CLOSE_NOTIFICATION_FULFILLED';
export const CLOSE_NOTIFICATION_REJECTED = 'CLOSE_NOTIFICATION_REJECTED';
export const CONFIRM_NOTIFICATION = 'CONFIRM_NOTIFICATION';
export const CONFIRM_NOTIFICATION_PENDING = 'CONFIRM_NOTIFICATION_PENDING';
export const CONFIRM_NOTIFICATION_FULFILLED = 'CONFIRM_NOTIFICATION_FULFILLED';
export const CONFIRM_NOTIFICATION_REJECTED = 'CONFIRM_NOTIFICATION_REJECTED';

/*
 * Deployments.
 */
export const OPEN_DEPLOYMENT = 'OPEN_DEPLOYMENT';
export const CLEAR_DEPLOYMENT = 'CLEAR_DEPLOYMENT';

// Fetch.
export const FETCH_DEPLOYMENTS = 'FETCH_DEPLOYMENTS';
export const FETCH_DEPLOYMENTS_PENDING = 'FETCH_DEPLOYMENTS_PENDING';
export const FETCH_DEPLOYMENTS_REJECTED = 'FETCH_DEPLOYMENTS_REJECTED';
export const FETCH_DEPLOYMENTS_FULFILLED = 'FETCH_DEPLOYMENTS_FULFILLED';

// Fetch.
export const FETCH_EXCLUDES = 'FETCH_EXCLUDES';
export const FETCH_EXCLUDES_PENDING = 'FETCH_EXCLUDES_PENDING';
export const FETCH_EXCLUDES_REJECTED = 'FETCH_EXCLUDES_REJECTED';
export const FETCH_EXCLUDES_FULFILLED = 'FETCH_EXCLUDES_FULFILLED';

export const UPDATE_EXCLUDES = 'UPDATE_EXCLUDES';
export const UPDATE_EXCLUDES_PENDING = 'UPDATE_EXCLUDES_PENDING';
export const UPDATE_EXCLUDES_REJECTED = 'UPDATE_EXCLUDES_REJECTED';
export const UPDATE_EXCLUDES_FULFILLED = 'UPDATE_EXCLUDES_FULFILLED';

// Mappings.
export const FETCH_MAPPINGS = 'FETCH_MAPPINGS';
export const FETCH_MAPPINGS_PENDING = 'FETCH_MAPPINGS_PENDING';
export const FETCH_MAPPINGS_REJECTED = 'FETCH_MAPPINGS_REJECTED';
export const FETCH_MAPPINGS_FULFILLED = 'FETCH_MAPPINGS_FULFILLED';

export const SAVE_MAPPINGS = 'SAVE_MAPPINGS';
export const SAVE_MAPPINGS_PENDING = 'SAVE_MAPPINGS_PENDING';
export const SAVE_MAPPINGS_REJECTED = 'SAVE_MAPPINGS_REJECTED';
export const SAVE_MAPPINGS_FULFILLED = 'SAVE_MAPPINGS_FULFILLED';

// Run.
export const RUN_DEPLOYMENT = 'RUN_DEPLOYMENT';
export const RUN_DEPLOYMENT_PENDING = 'RUN_DEPLOYMENT_PENDING';
export const RUN_DEPLOYMENT_REJECTED = 'RUN_DEPLOYMENT_REJECTED';
export const RUN_DEPLOYMENT_FULFILLED = 'RUN_DEPLOYMENT_FULFILLED';

/*
 * Auth.
 */

// Token.
export const LOADED_TOKEN = 'LOADED_TOKEN';
export const RECIEVED_TOKEN = 'RECIEVED_TOKEN';

// Login.
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const REDIRECT_LOGIN = 'REDIRECT_LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// Logout.
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Notifications
export const OPEN_EXCLUDES_NOTIFICATION = 'OPEN_RULE_NOTIFICATION';
export const CLOSE_EXCLUDES_NOTIFICATION = 'CLOSE_RULE_NOTIFICATION';
