# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build_and_test:
    working_directory: ~/repo
    parameters:
      v:
        type: string
        default: "8"
    docker:
      - image: circleci/node:<< parameters.v >>

    steps:
      - checkout
      - run: npm ci
      - run: npm run test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
      - run:
          name: Compress Artifacts
          command: tar -zcvf dist.tar.gz dist/
      - store_artifacts:
          path: dist.tar.gz

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test:
          name: build_and_test_node8
          v: "8"
      - build_and_test:
          name: build_and_test_node12
          v: "12"
      - build_and_test:
          name: build_and_test_node13
          v: "13"
  build_test_and_deploy:
    jobs:
      - build_and_test:
          v: "8" # Change this when we move to node 12.
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
